version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    container_name: redis

  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=postgres
    container_name: backend

  frontend:
    build: 
      context: ./example-frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: frontend
  
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: postgres