FROM php:8.1-fpm AS build

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       zlib1g-dev \
       g++ \
       git \
       libicu-dev \
       zip \
       libzip-dev \
       libpq-dev \
       curl \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/slim_app

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN git config --global user.email "kosenko.ou1@gmail.com" \
    && git config --global user.name "Kosenko Klym"

COPY . .

RUN composer install --no-dev --optimize-autoloader


FROM php:8.1-fpm

COPY --from=build /var/www/slim_app /var/www/slim_app
COPY --from=build /usr/local/bin/composer /usr/local/bin/composer

WORKDIR /var/www/slim_app

RUN chown -R www-data:www-data /var/www/slim_app

USER www-data

EXPOSE 9000

CMD ["php-fpm"]