version: '3.8'

services:
  simple-web-server:
    image: devopsdockeruh/simple-web-service
    build: .
    ports:
      - 8080:8080
    command: sh -c "server"
    container_name: simple-web-service-server